# Generated by Django 3.0.4 on 2020-03-21 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_item_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
    ]
