# Generated by Django 3.0.4 on 2020-03-21 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_remove_item_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
