# Generated by Django 3.0.4 on 2020-03-25 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_auto_20200324_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fullname',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
