# Generated by Django 3.0.4 on 2020-03-25 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_order_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='fullname',
            new_name='full_name',
        ),
    ]
