# Generated by Django 3.0.4 on 2020-03-26 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_auto_20200325_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproducts',
            name='id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
